version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/tuition_center
      - PORT=4000
      - CORS_ORIGINS=http://localhost:5173
      - JWT_ACCESS_SECRET=change_me
      - JWT_REFRESH_SECRET=change_me
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  mongo_data: